spring.application.name=oxtore-store
# ===============================
# Application
# ===============================
server.port=8081

# ===============================
# Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://store-db:5432/store-db
spring.datasource.username=oxtore
spring.datasource.password=oxtore
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===============================
# Connection Pool (Hikari)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.context=DEBUG

jwt.secret=your-super-secret-key-that-is-at-least-256-bits-long-for-production-use
jwt.expiration=86400000